# Generated by Django 5.0.6 on 2024-06-26 01:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('skill_icon', models.URLField(blank=True, max_length=100, null=True)),
                ('skill_description', models.CharField(blank=True, max_length=400, null=True)),
                ('category', models.CharField(max_length=30)),
                ('level', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
